seed: 49

experiment_name: "B2T"
wandb: false

float32_matmul_precision: "medium"
trainer:
  accelerator: "gpu"
  # devices: 1
  # precision: "32-true"
  # accumulate_grad_batches: 1
  val_check_interval: 0.5
  max_epochs: 6
  gradient_clip_val: 0.3
